Api Pitches Get Endpoint to use IPitchService and up-to-date objects
green-fox-academy/ferrilata-devilline pull request #14
Opened 2019-07-04 09:06 UTC by gagyizsofi

This time I avoided to move anything in a new directory, and also to write a new test that tests the content of what this endpoint gives back, because I'm trying to stick more strictly to the task itself.

2019-07-04 14:08 UTC, kskulikova approved these changes

2019-07-05 07:59 UTC, AlexTeper requested changes

2019-07-05 07:59 UTC, AlexTeper commented on ferrilata-devilline/Services/MockPitchService.cs
> +        public Pitches GetPitches()
Please make this method more readable

2019-07-05 08:23 UTC, AlexTeper approved these changes

2019-07-05 08:23 UTC, merged