Bootstrap added to Layout and GetBadgeLibrary
green-fox-academy/ferrilata-devilline pull request #16
Opened 2019-07-09 15:16 UTC by sabyanna

GetBadgeLibrary style and logic will be improved later, now it is functional

2019-07-09 20:08 UTC, kskulikova requested changes

2019-07-09 20:08 UTC, kskulikova commented on ferrilata-devilline.IntegrationTests/ferrilata-devilline.IntegrationTests.csproj
> +    <Folder Include="Scenarios\ApiControllers\AdminController\" />
(line 25) Unnecessary line: there is no AdminController class in the Test project, but because of this line here there is this warning:
![Screenshot 2019-07-09 at 21 10 57](https://user-images.githubusercontent.com/34596539/60918643-20c2af00-a294-11e9-9729-f43c68846ca4.png)

2019-07-09 20:08 UTC, kskulikova commented on ferrilata-devilline.IntegrationTests/Fixtures/TestContext.cs
> +        private TestServer Server;
Private fields' names should start with a lower-case letter

2019-07-09 20:08 UTC, kskulikova commented on ferrilata-devilline.IntegrationTests/Fixtures/HtmlReader.cs
> +            void ResponseFactory(AngleSharp.Io.VirtualResponse htmlResponse)
Nested methods can be avoided to make things simpler:
```
public static async Task<IHtmlDocument> GetDocumentAsync(HttpResponseMessage response)
        {
            var content = await response.Content.ReadAsStringAsync();
            Action<VirtualResponse> action = x => x.Address(response.RequestMessage.RequestUri)
                                                    .Status(response.StatusCode)
                                                    .Headers(response.Headers)
                                                    .Headers(response.Content.Headers)
                                                    .Content(content);
            
            var document = await BrowsingContext.New()
                .OpenAsync(action, CancellationToken.None);
            return (IHtmlDocument)document;
        }
```

2019-07-09 20:08 UTC, kskulikova commented on ferrilata-devilline.IntegrationTests/Scenarios/ViewControllers/BadgeControllerGetTests.cs
> +﻿using ferrilata_devilline.IntegrationTests.Fixtures;
2/4 tests failed:
- Returns_CorrenctNrOfObjects
- Returns_CorrectFieldsOfObjects

2019-07-10 12:16 UTC, drexeverest approved these changes

2019-07-10 15:10 UTC, merged