Fd 33 b
green-fox-academy/ferrilata-devilline pull request #18
Opened 2019-07-10 09:23 UTC by iaroslavm

My version of token generator

2019-07-10 11:51 UTC, sabyanna requested changes

2019-07-10 11:51 UTC, sabyanna commented on ferrilata-devilline/Services/Interfaces/ITokenService.cs
> +
10 - too many empty lines

2019-07-10 11:51 UTC, sabyanna commented on ferrilata-devilline/Startup.cs
> +
54-72 - this is needed for the validation, not for generating tokens

2019-07-10 14:55 UTC, sabyanna approved these changes

2019-07-12 10:32 UTC, drexeverest requested changes

2019-07-12 10:32 UTC, Suviii commented on ferrilata-devilline/Migrations/20190710090246_Test1.cs
> +}
You can remove empty migration files

2019-07-12 10:32 UTC, Suviii commented on ferrilata-devilline/Services/TokenService.cs
> +                Subject = new ClaimsIdentity(new Claim[]
The indentation is not the best here

2019-07-29 09:27 UTC, AlexTeper approved these changes

2019-07-29 13:16 UTC, merged